name: BuildAssistant
version: '1.0-SNAPSHOT'
main: jp.houlab.mochidsuki.buildAssistant.Main
api-version: '1.20'

commands:
  buildRoad:
    aliases: [br]
    description: ジャンパ
    permission: buildAssistant.command.buildRoad
    permission-message: Permission denied
    usage: jumppad [int] [int]